"""add_is_completed_to_historical_spreadsheets

Revision ID: 8a71126241c8
Revises: 20260609_0003
Create Date: 2026-06-09 12:42:23.226068
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8a71126241c8'
down_revision = '20260609_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_spreadsheets', sa.Column('is_completed', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_spreadsheets', 'is_completed')
    # ### end Alembic commands ###
